// ============================================================
//  FluxPP — DiagnosticUsageExamples.cpp
//
//  Reference patterns for how the Static Analyser and IR
//  Generator visitors integrate the diagnostic system.
//  This file is documentation-by-example; it does not need
//  to be compiled into your production binary.
// ============================================================

#include "diagnostic_engine.hpp"
#include "diagnose_helpers.hpp"
#include "diagnostic_builder.hpp"

// Assume these are generated by ANTLR:
//   FluxPPParser::AssignmentContext
//   FluxPPParser::FilterContext
//   FluxPPParser::FunctionCallContext
//   … etc.

namespace scripting::fluxpp::examples {

// ─────────────────────────────────────────────────────────────────────────────
//  0.  DRIVER SETUP
//      Create one engine; pass it to both visitors.
// ─────────────────────────────────────────────────────────────────────────────
void driverExample(const std::string& sourcePath,
                   const std::vector<std::string>& sourceLines) {
    DiagnosticEngine engine(sourcePath, sourceLines);

    // StaticAnalyzer analyser(engine, …);
    // IRGenerator    irGen(engine, …);
    // analyser.visit(parseTree);
    // if (!engine.hasErrors()) irGen.visit(parseTree);

    engine.printAll(std::cerr);
}


// ─────────────────────────────────────────────────────────────────────────────
//  1.  SSA001 — Reassignment to immutable variable
//      Triggered in StaticAnalyzer::visitAssignment
// ─────────────────────────────────────────────────────────────────────────────
void example_SSA001(DiagnosticEngine& engine,
                    antlr4::ParserRuleContext* ctx,
                    const std::string& varName,
                    uint32_t firstDeclLine)
{
    engine.report(ErrorCode::SSA001_IMMUTABLE_REASSIGNMENT)
        .at(ctx)
        .what(whatReassign(varName))
        .expected("LET variables are immutable and cannot be reassigned")
        .found(firstDeclaredAt(varName, firstDeclLine)
               + "; a second assignment appears here")
        .fix("Use a different name for the new variable, or "
             "remove the duplicate LET statement");
}


// ─────────────────────────────────────────────────────────────────────────────
//  2.  REF003 — Unknown column in SET
//      Triggered in StaticAnalyzer::visitSet
// ─────────────────────────────────────────────────────────────────────────────
void example_REF003_set(DiagnosticEngine& engine,
                         antlr4::Token* idToken,
                         const std::string& colName)
{
    engine.report(ErrorCode::REF003_UNKNOWN_COLUMN)
        .at(idToken)
        .what(whatUnknownCol(colName))
        .expected("An existing data frame column")
        .found("'" + colName + "' is not present in the data frame "
               "at this point in the script")
        .fix("Use CREATE " + colName + " AS … to introduce the column first, "
             "or check for a typo in the column name");
}


// ─────────────────────────────────────────────────────────────────────────────
//  3.  TYP003 — Condition not bool (KEEP IF)
//      Triggered in StaticAnalyzer::visitFilter
// ─────────────────────────────────────────────────────────────────────────────
void example_TYP003_keepif(DiagnosticEngine& engine,
                             antlr4::ParserRuleContext* exprCtx,
                             Type actualType, Dim actualDim)
{
    engine.report(ErrorCode::TYP003_CONDITION_NOT_BOOL)
        .at(exprCtx)
        .what("KEEP IF condition does not evaluate to bool")
        .expected(expBoolVector())
        .found(foundTypeDim(actualType, actualDim))
        .fix("Apply a comparison operator to produce a bool vector, "
             "e.g.  KEEP IF col > 0");
}


// ─────────────────────────────────────────────────────────────────────────────
//  4.  DIM001 — Expected vector, got scalar (KEEP IF)
//      Triggered in StaticAnalyzer::visitFilter (after type passes)
// ─────────────────────────────────────────────────────────────────────────────
void example_DIM001_keepif(DiagnosticEngine& engine,
                             antlr4::ParserRuleContext* exprCtx)
{
    engine.report(ErrorCode::DIM001_EXPECTED_VECTOR_GOT_SCALAR)
        .at(exprCtx)
        .what("KEEP IF requires a vector mask but the condition is scalar")
        .expected(expBoolVector())
        .found("bool scalar expression (would affect all rows equally)")
        .fix("Reference at least one data frame column in the condition "
             "so that it is evaluated per-row");
}


// ─────────────────────────────────────────────────────────────────────────────
//  5.  TYP007 — SET type mismatch
//      Triggered in StaticAnalyzer::visitSet
// ─────────────────────────────────────────────────────────────────────────────
void example_TYP007(DiagnosticEngine& engine,
                     antlr4::ParserRuleContext* exprCtx,
                     const std::string& colName,
                     Type colType, Type exprType, Dim exprDim)
{
    engine.report(ErrorCode::TYP007_SET_TYPE_MISMATCH)
        .at(exprCtx)
        .what("SET expression type '" + fmtType(exprType)
              + "' does not match column '" + colName + "' type '"
              + fmtType(colType) + "'")
        .expected(expSameTypeAs(colName, colType))
        .found(foundTypeDim(exprType, exprDim))
        .fix(fixCastTo(colType));
}


// ─────────────────────────────────────────────────────────────────────────────
//  6.  TYP005 — CLAMP bounds type mismatch
//      Triggered in StaticAnalyzer::visitClamp
// ─────────────────────────────────────────────────────────────────────────────
void example_TYP005(DiagnosticEngine& engine,
                     antlr4::ParserRuleContext* clampCtx,
                     Type fromType, Type toType)
{
    engine.report(ErrorCode::TYP005_CLAMP_BOUNDS_TYPE_MISMATCH)
        .at(clampCtx)
        .what("CLAMP 'from' and 'to' bounds must share the same type")
        .expected("Both bounds of the same type (real or timestamp)")
        .found("'from' is " + fmtType(fromType)
               + ", 'to' is " + fmtType(toType))
        .fix("Cast one of the bounds so that both are the same type");
}


// ─────────────────────────────────────────────────────────────────────────────
//  7.  RNG001 — CLAMP empty / inverted range
//      Triggered in StaticAnalyzer (static) or IRGenerator (runtime fold)
// ─────────────────────────────────────────────────────────────────────────────
void example_RNG001(DiagnosticEngine& engine,
                     antlr4::ParserRuleContext* clampCtx,
                     double fromVal, double toVal)
{
    engine.report(ErrorCode::RNG001_CLAMP_EMPTY_RANGE)
        .at(clampCtx)
        .what("CLAMP range is empty: 'from' ("
              + std::to_string(fromVal)
              + ") >= 'to' (" + std::to_string(toVal) + ")")
        .expected("'to' > 'from' so that the clamp range contains at least one value")
        .found("to - from = " + std::to_string(toVal - fromVal)
               + " (must be > 0)")
        .fix("Swap 'from' and 'to', or adjust the bound expressions");
}


// ─────────────────────────────────────────────────────────────────────────────
//  8.  ARG001 — Wrong argument count
//      Triggered in StaticAnalyzer::visitFunctionCall
// ─────────────────────────────────────────────────────────────────────────────
void example_ARG001(DiagnosticEngine& engine,
                     antlr4::ParserRuleContext* callCtx,
                     const std::string& fnName,
                     uint32_t expected, uint32_t provided)
{
    engine.report(ErrorCode::ARG001_WRONG_ARG_COUNT)
        .at(callCtx)
        .what(whatWrongArgCount(fnName, expected, provided))
        .expected(std::to_string(expected) + " argument(s)")
        .found(foundArgCount(provided))
        .fix("Check the function signature for '" + fnName + "' and "
             "provide exactly " + std::to_string(expected) + " argument(s)");
}


// ─────────────────────────────────────────────────────────────────────────────
//  9.  TYP004 — Ternary branch type mismatch
//      Triggered in StaticAnalyzer::visitTernary
// ─────────────────────────────────────────────────────────────────────────────
void example_TYP004(DiagnosticEngine& engine,
                     antlr4::ParserRuleContext* ternaryCtx,
                     Type trueType, Dim trueDim,
                     Type falseType, Dim falseDim)
{
    engine.report(ErrorCode::TYP004_TERNARY_BRANCH_MISMATCH)
        .at(ternaryCtx)
        .what("Ternary branches have incompatible types")
        .expected("Both branches must evaluate to the same type")
        .found("true-branch: " + fmtTypeDim(trueType, trueDim)
               + ", false-branch: " + fmtTypeDim(falseType, falseDim))
        .fix(fixCastTo(trueType) + " on the false branch, or vice-versa");
}


// ─────────────────────────────────────────────────────────────────────────────
// 10.  REF006 — RENAME destination conflict, with secondary note
//      Triggered in StaticAnalyzer::visitRename
// ─────────────────────────────────────────────────────────────────────────────
void example_REF006(DiagnosticEngine& engine,
                     antlr4::Token* dstToken,
                     antlr4::Token* firstDeclToken,
                     const std::string& dstName)
{
    engine.report(ErrorCode::REF006_RENAME_DST_CONFLICT)
        .at(dstToken)
        .what("RENAME destination '" + dstName + "' is already in use")
        .expected("A name that is not yet used as a variable or column")
        .found("'" + dstName + "' already declared")
        .note("'" + dstName + "' was first declared here", firstDeclToken)
        .fix("Choose a different destination name, or REMOVE the existing '"
             + dstName + "' column before renaming");
}


// ─────────────────────────────────────────────────────────────────────────────
// 11.  W_SEM001 — REMOVE will delete all columns (warning)
//      Triggered in StaticAnalyzer::visitDropCol
// ─────────────────────────────────────────────────────────────────────────────
void example_W_SEM001(DiagnosticEngine& engine,
                       antlr4::ParserRuleContext* removeCtx)
{
    engine.report(ErrorCode::W_SEM001_REMOVE_ALL_COLUMNS)
        .at(removeCtx)
        .what("REMOVE will drop every column, leaving an empty data frame")
        .expected("At least one column to remain after REMOVE")
        .found("The listed columns cover all columns in the data frame")
        .fix("Review the column list — if intentional, ignore this warning");
}


// ─────────────────────────────────────────────────────────────────────────────
// 12.  RUN002 — KEEP IF all-false at runtime (IR Generator)
//      Triggered in IRGenerator after evaluating the mask
// ─────────────────────────────────────────────────────────────────────────────
void example_RUN002(DiagnosticEngine& engine,
                     antlr4::ParserRuleContext* filterCtx,
                     uint64_t rowCount)
{
    engine.report(ErrorCode::RUN002_FILTER_ALL_FALSE)
        .at(filterCtx)
        .what("KEEP IF mask is all-false; all " + std::to_string(rowCount)
              + " rows were dropped")
        .expected("At least one row to satisfy the filter condition")
        .found("No row matched the condition; data frame is now empty")
        .fix("Re-examine the filter condition or the data — "
             "no input row satisfied it");
}


// ─────────────────────────────────────────────────────────────────────────────
// 13.  RUN001 — Division by zero at runtime (IR Generator)
// ─────────────────────────────────────────────────────────────────────────────
void example_RUN001(DiagnosticEngine& engine,
                     antlr4::ParserRuleContext* divCtx)
{
    engine.report(ErrorCode::RUN001_DIVISION_BY_ZERO)
        .at(divCtx)
        .what("Division by zero encountered at runtime")
        .expected("A non-zero divisor")
        .found("One or more elements of the divisor are zero")
        .fix("Guard the denominator with a FILL or ternary expression, "
             "e.g.  numerator / (0.0001 IF denom == 0 ELSE denom)");
}

} // namespace fluxpp::examples
