// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RETURNTYPES_H_
#define FLATBUFFERS_GENERATED_RETURNTYPES_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct StringDFResult;
struct StringDFResultBuilder;

struct TypeInferenceResult;
struct TypeInferenceResultBuilder;

struct ColumnTypeInferenceResult;
struct ColumnTypeInferenceResultBuilder;

struct DFTypeInferenceResult;
struct DFTypeInferenceResultBuilder;

struct ColumnNullCheckResult;
struct ColumnNullCheckResultBuilder;

struct DFNullCheckResult;
struct DFNullCheckResultBuilder;

struct FieldSchema;
struct FieldSchemaBuilder;

struct DFSchema;
struct DFSchemaBuilder;

struct StringDFResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringDFResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_ROWS = 6,
    VT_COLS = 8
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *data() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DATA);
  }
  int32_t rows() const {
    return GetField<int32_t>(VT_ROWS, 0);
  }
  int32_t cols() const {
    return GetField<int32_t>(VT_COLS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.VerifyVectorOfStrings(data()) &&
           VerifyField<int32_t>(verifier, VT_ROWS, 4) &&
           VerifyField<int32_t>(verifier, VT_COLS, 4) &&
           verifier.EndTable();
  }
};

struct StringDFResultBuilder {
  typedef StringDFResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> data) {
    fbb_.AddOffset(StringDFResult::VT_DATA, data);
  }
  void add_rows(int32_t rows) {
    fbb_.AddElement<int32_t>(StringDFResult::VT_ROWS, rows, 0);
  }
  void add_cols(int32_t cols) {
    fbb_.AddElement<int32_t>(StringDFResult::VT_COLS, cols, 0);
  }
  explicit StringDFResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StringDFResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StringDFResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StringDFResult> CreateStringDFResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> data = 0,
    int32_t rows = 0,
    int32_t cols = 0) {
  StringDFResultBuilder builder_(_fbb);
  builder_.add_cols(cols);
  builder_.add_rows(rows);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StringDFResult> CreateStringDFResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *data = nullptr,
    int32_t rows = 0,
    int32_t cols = 0) {
  auto data__ = data ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*data) : 0;
  return CreateStringDFResult(
      _fbb,
      data__,
      rows,
      cols);
}

struct TypeInferenceResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TypeInferenceResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_CONFIDENCE = 6
  };
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  float confidence() const {
    return GetField<float>(VT_CONFIDENCE, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyField<float>(verifier, VT_CONFIDENCE, 4) &&
           verifier.EndTable();
  }
};

struct TypeInferenceResultBuilder {
  typedef TypeInferenceResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(TypeInferenceResult::VT_TYPE, type);
  }
  void add_confidence(float confidence) {
    fbb_.AddElement<float>(TypeInferenceResult::VT_CONFIDENCE, confidence, 0.0f);
  }
  explicit TypeInferenceResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TypeInferenceResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TypeInferenceResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TypeInferenceResult> CreateTypeInferenceResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    float confidence = 0.0f) {
  TypeInferenceResultBuilder builder_(_fbb);
  builder_.add_confidence(confidence);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TypeInferenceResult> CreateTypeInferenceResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *type = nullptr,
    float confidence = 0.0f) {
  auto type__ = type ? _fbb.CreateString(type) : 0;
  return CreateTypeInferenceResult(
      _fbb,
      type__,
      confidence);
}

struct ColumnTypeInferenceResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColumnTypeInferenceResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COLUMN_NAME = 4,
    VT_PRIMARY_TYPE = 6,
    VT_ALTERNATIVES = 8,
    VT_ORIGINAL_TYPE = 10,
    VT_NULL_PERCENT = 12,
    VT_UNIQUE_COUNT = 14
  };
  const ::flatbuffers::String *column_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COLUMN_NAME);
  }
  const TypeInferenceResult *primary_type() const {
    return GetPointer<const TypeInferenceResult *>(VT_PRIMARY_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<TypeInferenceResult>> *alternatives() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<TypeInferenceResult>> *>(VT_ALTERNATIVES);
  }
  const ::flatbuffers::String *original_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ORIGINAL_TYPE);
  }
  float null_percent() const {
    return GetField<float>(VT_NULL_PERCENT, 0.0f);
  }
  uint64_t unique_count() const {
    return GetField<uint64_t>(VT_UNIQUE_COUNT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COLUMN_NAME) &&
           verifier.VerifyString(column_name()) &&
           VerifyOffset(verifier, VT_PRIMARY_TYPE) &&
           verifier.VerifyTable(primary_type()) &&
           VerifyOffset(verifier, VT_ALTERNATIVES) &&
           verifier.VerifyVector(alternatives()) &&
           verifier.VerifyVectorOfTables(alternatives()) &&
           VerifyOffset(verifier, VT_ORIGINAL_TYPE) &&
           verifier.VerifyString(original_type()) &&
           VerifyField<float>(verifier, VT_NULL_PERCENT, 4) &&
           VerifyField<uint64_t>(verifier, VT_UNIQUE_COUNT, 8) &&
           verifier.EndTable();
  }
};

struct ColumnTypeInferenceResultBuilder {
  typedef ColumnTypeInferenceResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_column_name(::flatbuffers::Offset<::flatbuffers::String> column_name) {
    fbb_.AddOffset(ColumnTypeInferenceResult::VT_COLUMN_NAME, column_name);
  }
  void add_primary_type(::flatbuffers::Offset<TypeInferenceResult> primary_type) {
    fbb_.AddOffset(ColumnTypeInferenceResult::VT_PRIMARY_TYPE, primary_type);
  }
  void add_alternatives(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<TypeInferenceResult>>> alternatives) {
    fbb_.AddOffset(ColumnTypeInferenceResult::VT_ALTERNATIVES, alternatives);
  }
  void add_original_type(::flatbuffers::Offset<::flatbuffers::String> original_type) {
    fbb_.AddOffset(ColumnTypeInferenceResult::VT_ORIGINAL_TYPE, original_type);
  }
  void add_null_percent(float null_percent) {
    fbb_.AddElement<float>(ColumnTypeInferenceResult::VT_NULL_PERCENT, null_percent, 0.0f);
  }
  void add_unique_count(uint64_t unique_count) {
    fbb_.AddElement<uint64_t>(ColumnTypeInferenceResult::VT_UNIQUE_COUNT, unique_count, 0);
  }
  explicit ColumnTypeInferenceResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColumnTypeInferenceResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColumnTypeInferenceResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColumnTypeInferenceResult> CreateColumnTypeInferenceResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> column_name = 0,
    ::flatbuffers::Offset<TypeInferenceResult> primary_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<TypeInferenceResult>>> alternatives = 0,
    ::flatbuffers::Offset<::flatbuffers::String> original_type = 0,
    float null_percent = 0.0f,
    uint64_t unique_count = 0) {
  ColumnTypeInferenceResultBuilder builder_(_fbb);
  builder_.add_unique_count(unique_count);
  builder_.add_null_percent(null_percent);
  builder_.add_original_type(original_type);
  builder_.add_alternatives(alternatives);
  builder_.add_primary_type(primary_type);
  builder_.add_column_name(column_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ColumnTypeInferenceResult> CreateColumnTypeInferenceResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *column_name = nullptr,
    ::flatbuffers::Offset<TypeInferenceResult> primary_type = 0,
    const std::vector<::flatbuffers::Offset<TypeInferenceResult>> *alternatives = nullptr,
    const char *original_type = nullptr,
    float null_percent = 0.0f,
    uint64_t unique_count = 0) {
  auto column_name__ = column_name ? _fbb.CreateString(column_name) : 0;
  auto alternatives__ = alternatives ? _fbb.CreateVector<::flatbuffers::Offset<TypeInferenceResult>>(*alternatives) : 0;
  auto original_type__ = original_type ? _fbb.CreateString(original_type) : 0;
  return CreateColumnTypeInferenceResult(
      _fbb,
      column_name__,
      primary_type,
      alternatives__,
      original_type__,
      null_percent,
      unique_count);
}

struct DFTypeInferenceResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DFTypeInferenceResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COLUMNS = 4,
    VT_INFERENCE_RESULT = 6,
    VT_IMPORTED_ROWS = 8
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *columns() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_COLUMNS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ColumnTypeInferenceResult>> *inference_result() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ColumnTypeInferenceResult>> *>(VT_INFERENCE_RESULT);
  }
  uint64_t imported_rows() const {
    return GetField<uint64_t>(VT_IMPORTED_ROWS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COLUMNS) &&
           verifier.VerifyVector(columns()) &&
           verifier.VerifyVectorOfStrings(columns()) &&
           VerifyOffset(verifier, VT_INFERENCE_RESULT) &&
           verifier.VerifyVector(inference_result()) &&
           verifier.VerifyVectorOfTables(inference_result()) &&
           VerifyField<uint64_t>(verifier, VT_IMPORTED_ROWS, 8) &&
           verifier.EndTable();
  }
};

struct DFTypeInferenceResultBuilder {
  typedef DFTypeInferenceResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_columns(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> columns) {
    fbb_.AddOffset(DFTypeInferenceResult::VT_COLUMNS, columns);
  }
  void add_inference_result(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ColumnTypeInferenceResult>>> inference_result) {
    fbb_.AddOffset(DFTypeInferenceResult::VT_INFERENCE_RESULT, inference_result);
  }
  void add_imported_rows(uint64_t imported_rows) {
    fbb_.AddElement<uint64_t>(DFTypeInferenceResult::VT_IMPORTED_ROWS, imported_rows, 0);
  }
  explicit DFTypeInferenceResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DFTypeInferenceResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DFTypeInferenceResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DFTypeInferenceResult> CreateDFTypeInferenceResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> columns = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ColumnTypeInferenceResult>>> inference_result = 0,
    uint64_t imported_rows = 0) {
  DFTypeInferenceResultBuilder builder_(_fbb);
  builder_.add_imported_rows(imported_rows);
  builder_.add_inference_result(inference_result);
  builder_.add_columns(columns);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DFTypeInferenceResult> CreateDFTypeInferenceResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *columns = nullptr,
    const std::vector<::flatbuffers::Offset<ColumnTypeInferenceResult>> *inference_result = nullptr,
    uint64_t imported_rows = 0) {
  auto columns__ = columns ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*columns) : 0;
  auto inference_result__ = inference_result ? _fbb.CreateVector<::flatbuffers::Offset<ColumnTypeInferenceResult>>(*inference_result) : 0;
  return CreateDFTypeInferenceResult(
      _fbb,
      columns__,
      inference_result__,
      imported_rows);
}

struct ColumnNullCheckResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColumnNullCheckResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NULL_ROWS = 4,
    VT_NULL_COUNT = 6,
    VT_NULL_PERCENT = 8
  };
  const StringDFResult *null_rows() const {
    return GetPointer<const StringDFResult *>(VT_NULL_ROWS);
  }
  uint64_t null_count() const {
    return GetField<uint64_t>(VT_NULL_COUNT, 0);
  }
  float null_percent() const {
    return GetField<float>(VT_NULL_PERCENT, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NULL_ROWS) &&
           verifier.VerifyTable(null_rows()) &&
           VerifyField<uint64_t>(verifier, VT_NULL_COUNT, 8) &&
           VerifyField<float>(verifier, VT_NULL_PERCENT, 4) &&
           verifier.EndTable();
  }
};

struct ColumnNullCheckResultBuilder {
  typedef ColumnNullCheckResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_null_rows(::flatbuffers::Offset<StringDFResult> null_rows) {
    fbb_.AddOffset(ColumnNullCheckResult::VT_NULL_ROWS, null_rows);
  }
  void add_null_count(uint64_t null_count) {
    fbb_.AddElement<uint64_t>(ColumnNullCheckResult::VT_NULL_COUNT, null_count, 0);
  }
  void add_null_percent(float null_percent) {
    fbb_.AddElement<float>(ColumnNullCheckResult::VT_NULL_PERCENT, null_percent, 0.0f);
  }
  explicit ColumnNullCheckResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColumnNullCheckResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColumnNullCheckResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColumnNullCheckResult> CreateColumnNullCheckResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<StringDFResult> null_rows = 0,
    uint64_t null_count = 0,
    float null_percent = 0.0f) {
  ColumnNullCheckResultBuilder builder_(_fbb);
  builder_.add_null_count(null_count);
  builder_.add_null_percent(null_percent);
  builder_.add_null_rows(null_rows);
  return builder_.Finish();
}

struct DFNullCheckResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DFNullCheckResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COLUMNS = 4,
    VT_NULL_RESULTS = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *columns() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_COLUMNS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ColumnNullCheckResult>> *null_results() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ColumnNullCheckResult>> *>(VT_NULL_RESULTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COLUMNS) &&
           verifier.VerifyVector(columns()) &&
           verifier.VerifyVectorOfStrings(columns()) &&
           VerifyOffset(verifier, VT_NULL_RESULTS) &&
           verifier.VerifyVector(null_results()) &&
           verifier.VerifyVectorOfTables(null_results()) &&
           verifier.EndTable();
  }
};

struct DFNullCheckResultBuilder {
  typedef DFNullCheckResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_columns(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> columns) {
    fbb_.AddOffset(DFNullCheckResult::VT_COLUMNS, columns);
  }
  void add_null_results(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ColumnNullCheckResult>>> null_results) {
    fbb_.AddOffset(DFNullCheckResult::VT_NULL_RESULTS, null_results);
  }
  explicit DFNullCheckResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DFNullCheckResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DFNullCheckResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DFNullCheckResult> CreateDFNullCheckResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> columns = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ColumnNullCheckResult>>> null_results = 0) {
  DFNullCheckResultBuilder builder_(_fbb);
  builder_.add_null_results(null_results);
  builder_.add_columns(columns);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DFNullCheckResult> CreateDFNullCheckResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *columns = nullptr,
    const std::vector<::flatbuffers::Offset<ColumnNullCheckResult>> *null_results = nullptr) {
  auto columns__ = columns ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*columns) : 0;
  auto null_results__ = null_results ? _fbb.CreateVector<::flatbuffers::Offset<ColumnNullCheckResult>>(*null_results) : 0;
  return CreateDFNullCheckResult(
      _fbb,
      columns__,
      null_results__);
}

struct FieldSchema FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FieldSchemaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TYPE = 6,
    VT_NULL_PERCENT = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const ::flatbuffers::String *null_percent() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NULL_PERCENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyOffset(verifier, VT_NULL_PERCENT) &&
           verifier.VerifyString(null_percent()) &&
           verifier.EndTable();
  }
};

struct FieldSchemaBuilder {
  typedef FieldSchema Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(FieldSchema::VT_NAME, name);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(FieldSchema::VT_TYPE, type);
  }
  void add_null_percent(::flatbuffers::Offset<::flatbuffers::String> null_percent) {
    fbb_.AddOffset(FieldSchema::VT_NULL_PERCENT, null_percent);
  }
  explicit FieldSchemaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FieldSchema> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FieldSchema>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FieldSchema> CreateFieldSchema(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> null_percent = 0) {
  FieldSchemaBuilder builder_(_fbb);
  builder_.add_null_percent(null_percent);
  builder_.add_type(type);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FieldSchema> CreateFieldSchemaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *type = nullptr,
    const char *null_percent = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto type__ = type ? _fbb.CreateString(type) : 0;
  auto null_percent__ = null_percent ? _fbb.CreateString(null_percent) : 0;
  return CreateFieldSchema(
      _fbb,
      name__,
      type__,
      null_percent__);
}

struct DFSchema FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DFSchemaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FIELDS = 4,
    VT_ROWS = 6,
    VT_MEMORY_SIZE_FILE = 8,
    VT_MEMORY_SIZE_COMPACT = 10
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<FieldSchema>> *fields() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FieldSchema>> *>(VT_FIELDS);
  }
  int32_t rows() const {
    return GetField<int32_t>(VT_ROWS, 0);
  }
  uint64_t memory_size_file() const {
    return GetField<uint64_t>(VT_MEMORY_SIZE_FILE, 0);
  }
  uint64_t memory_size_compact() const {
    return GetField<uint64_t>(VT_MEMORY_SIZE_COMPACT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FIELDS) &&
           verifier.VerifyVector(fields()) &&
           verifier.VerifyVectorOfTables(fields()) &&
           VerifyField<int32_t>(verifier, VT_ROWS, 4) &&
           VerifyField<uint64_t>(verifier, VT_MEMORY_SIZE_FILE, 8) &&
           VerifyField<uint64_t>(verifier, VT_MEMORY_SIZE_COMPACT, 8) &&
           verifier.EndTable();
  }
};

struct DFSchemaBuilder {
  typedef DFSchema Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fields(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FieldSchema>>> fields) {
    fbb_.AddOffset(DFSchema::VT_FIELDS, fields);
  }
  void add_rows(int32_t rows) {
    fbb_.AddElement<int32_t>(DFSchema::VT_ROWS, rows, 0);
  }
  void add_memory_size_file(uint64_t memory_size_file) {
    fbb_.AddElement<uint64_t>(DFSchema::VT_MEMORY_SIZE_FILE, memory_size_file, 0);
  }
  void add_memory_size_compact(uint64_t memory_size_compact) {
    fbb_.AddElement<uint64_t>(DFSchema::VT_MEMORY_SIZE_COMPACT, memory_size_compact, 0);
  }
  explicit DFSchemaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DFSchema> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DFSchema>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DFSchema> CreateDFSchema(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FieldSchema>>> fields = 0,
    int32_t rows = 0,
    uint64_t memory_size_file = 0,
    uint64_t memory_size_compact = 0) {
  DFSchemaBuilder builder_(_fbb);
  builder_.add_memory_size_compact(memory_size_compact);
  builder_.add_memory_size_file(memory_size_file);
  builder_.add_rows(rows);
  builder_.add_fields(fields);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DFSchema> CreateDFSchemaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<FieldSchema>> *fields = nullptr,
    int32_t rows = 0,
    uint64_t memory_size_file = 0,
    uint64_t memory_size_compact = 0) {
  auto fields__ = fields ? _fbb.CreateVector<::flatbuffers::Offset<FieldSchema>>(*fields) : 0;
  return CreateDFSchema(
      _fbb,
      fields__,
      rows,
      memory_size_file,
      memory_size_compact);
}

#endif  // FLATBUFFERS_GENERATED_RETURNTYPES_H_
